# Generated by Django 5.2 on 2025-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('cake_name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('cancelled', 'Отменён')], default='waiting', max_length=20)),
            ],
        ),
    ]
