# Generated by Django 5.2 on 2025-05-07 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake_name',
            field=models.CharField(choices=[('red_cake', 'Красный бархат'), ('honet', 'Медовик'), ('Apricot', 'Абрикосовый'), ('Vanilla', 'Ванильный'), ('Poppy', 'Маковый')], max_length=255),
        ),
    ]
