# Generated by Django 5.2 on 2025-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_order_date_alter_order_cake_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cake_name',
            field=models.CharField(choices=[('Red_cake', 'Красный бархат'), ('Honey', 'Медовик'), ('Apricot', 'Абрикосовый'), ('Vanilla', 'Ванильный'), ('Poppy', 'Маковый')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
